---
- snmp_facts:
    host: all
    version: v2c
    community: snmpPW
  delegate_to: localhost

- debug:
        msg: "due to vagrant for snmp to work from mgmt to sw we need more ports forwarding&tell snmp_facts to use them or create additonal mgmt network"

#- name: Generate links
#  template: src={{template|default('links.j2')}} dest=./{{output|default('links.txt')}}