---
- hosts: all
  tasks:
  - name: RestAPi Test - Show something
    uri: 
      url: https://10.0.2.2:{{ api_port }}/nclu/v1/rpc
      method: POST
      user: "vagrant"
      password: "vagrant"
      validate_certs: no
      return_content: yes
      body: {"cmd": "show lldp json"}
      body_format: json
      status_code: 200
    register: output
  
  - name: Result
    debug:
      var: output


#next use var to specify ports per sw....